docs: Add import docs in vue-cli docs
windicss/docs pull request #148
Opened 2021-12-30 13:25 UTC by Shimada666

I am a vue2 & ts developer, and when I use `vue add windicss` according to the document, it does not take effect. After checking the vue cli plugin documentation, I found that I need to add `import 'windi.css'` in  my main.ts to take effect, so I added it.

2021-12-30 13:40 UTC, Techassi commented
Great addition! I would suggest to structure the page similar to the [Vite](https://windicss.org/integrations/vite.html) one. For example:

````md
## Install

Install using Vue CLI. (Vue CLI 4+ is recommended)

```
vue add windicss
```

Then, add the configuartion

```js vue.config.js
...
```

And finally, import `windi.css` in your entry

```js main.js
import 'windi.css'
```

````

2021-12-31 03:59 UTC, Shimada666 commented
Yeah, I think using the same structure is a great suggestion. However, there is an Import part in `vue-cli-plugin-windicss` document but not in this document, and the other parts are basically the same. Is it a better choice to fill in the missing part and keep it consistent with the `vue-cli-plugin-windicss` document?

![image](https://user-images.githubusercontent.com/33391300/147802205-bd1cb7d8-56bd-4466-929d-e22258d6eb76.png)

![image](https://user-images.githubusercontent.com/33391300/147802502-a9956384-9d5d-49c3-9b3e-89fbba827f03.png)

2021-12-31 09:45 UTC, Techassi commented
I think keeping it consistent with the Vite (and Rollup) integration is the way forward. Having a consistent structure in the official docs is a plus point (especially for new users).

Regarding the `vue-cli-plugin-windicss` README: If we feel it is neccesary to mirror the docs we can do this later. Or you can open a PR :)

2021-12-31 11:30 UTC, Shimada666 commented
> I think keeping it consistent with the Vite (and Rollup) integration is the way forward. Having a consistent structure in the official docs is a plus point (especially for new users).
> 
> Regarding the `vue-cli-plugin-windicss` README: If we feel it is neccesary to mirror the docs we can do this later. Or you can open a PR :)

Okay, I pushed the document again, please check if they meet expectations. Thank you for your comments!

2021-12-31 15:26 UTC, Techassi requested changes
Please see the comment below. This rest is fine :)

2021-12-31 15:26 UTC, Techassi commented on integrations/vue-cli.md
> -:warning: This module is a pre-release, please report any [issues](https://github.com/windicss/vue-cli-plugin-windicss/issues) you find.
Please re-add this notice

2022-01-01 05:11 UTC, Shimada666 commented on integrations/vue-cli.md
> -:warning: This module is a pre-release, please report any [issues](https://github.com/windicss/vue-cli-plugin-windicss/issues) you find.
done :)

2022-01-01 11:05 UTC, Techassi approved these changes

2022-01-01 11:07 UTC, merged

2022-01-01 11:07 UTC, hannoeru commented
Thanks!