Add Specific Instructions for Svelte Kit
windicss/docs pull request #64
Opened 2021-05-06 21:11 UTC by alteredorange

Get windi working with the latest svelte kit.

2021-05-07 05:10 UTC, alexanderniebuhr requested changes
thanks for you PR. I have reviewed it and marked things to change for you

2021-05-07 05:10 UTC, alexanderniebuhr commented on integrations/svelte.md
> +### Svelte Kit (As of 1.0.0-next.100)
I would prefer if the instruction part is actually moved down under the vanilla Svelte section please

2021-05-07 05:10 UTC, alexanderniebuhr commented on integrations/svelte.md
> +You should only need to install the vite plugin, not the svelte-preprocess plugin - (`npm i -D vite-plugin-windicss`). Then add the plugin to your svelte config. Don't forget to add `import "virtual:
Change to something like, you also should include an very basic example of  `$layout.svelte` file

Svelte Kit uses vite as a bundler, therefore we suggest to use our [vite plugin](https://windicss.org/integrations/vite.html)
Add the plugin to your svelte config. 
After that add `import "virtual:windi.css"` to the top of your $layout.svelte file.

2021-05-07 05:10 UTC, alexanderniebuhr commented on integrations/svelte.md
> +				WindiCSS.default()
the import of WindiCSS npm package seems to be missing

2021-05-07 15:24 UTC, alteredorange reviewed
Sounds good, I'll add those changes!

2021-05-08 17:19 UTC, alexanderniebuhr approved these changes
/lgtm @hannoeru

2021-05-08 18:20 UTC, merged